version: '3.8'
services:
  redisdb:
    image: redis:alpine3.17
    ports:
      - 6379:6379
  
  postgresql:
    image: postgres:alpine3.17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust 
      - POSTGRES_USER=testaccount
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=testdb 
    # volumes:
    #   - ./docker/postgres:/var/lib/postgresql
    

